export const farmProducts = [
  {
    id: "1",
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: "1000",
    description: "Fresh, organic tomatoes grown without pesticides.",
    stock: "120",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Port-harcourt Greens",
      about:
        "Port-harcourt Greens is committed to sustainable farming practices, focusing on organic methods that promote soil health and biodiversity. Located in the lush region of Port-harcourt, our farm produces high-quality vegetables that nourish both body and planet.",
      city: "Port-harcourt",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "2",
    name: "Fresh Spinach",
    category: "Vegetables",
    price: "800",
    description: "Nutritious spinach, harvested at peak freshness.",
    stock: "100",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Green Valley Farms",
      about:
        "At Green Valley Farms, we pride ourselves on our commitment to organic practices and community welfare. Our spinach is grown in nutrient-rich soil, ensuring that every leaf is packed with vitamins and minerals. We believe in growing food that not only nourishes our bodies but also supports local ecosystems.",
      city: "Ibadan",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "3",
    name: "Crisp Lettuce",
    category: "Vegetables",
    price: "500",
    description: "Crisp and refreshing lettuce perfect for salads.",
    stock: "150",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Sunny Acres Farm",
      about:
        "Sunny Acres Farm is dedicated to producing fresh, high-quality vegetables. Our lettuce is grown in an environment that allows it to thrive naturally, without the use of harmful chemicals. We are passionate about sustainability and aim to provide our community with healthy food options.",
      city: "Lagos",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "4",
    name: "Juicy Watermelons",
    category: "Fruits",
    price: "1200",
    description: "Sweet and juicy watermelons, perfect for summer.",
    stock: "80",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Tropical Fruit Farm",
      about:
        "Tropical Fruit Farm specializes in growing the sweetest, juiciest fruits in a sustainable manner. Our watermelons are grown under the warm sun, nurtured by the rich soils of our farm. We prioritize ecological balance and the health of our customers with every fruit we produce.",
      city: "Benin City",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "5",
    name: "Herbal Basil",
    category: "Herbs",
    price: "600",
    description: "Fresh basil, perfect for culinary use.",
    stock: "200",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Herb Haven",
      about:
        "Herb Haven is a small family-owned farm that focuses on growing a variety of herbs, including basil. Our herbs are grown without synthetic fertilizers, ensuring that you receive the freshest, most flavorful ingredients for your cooking. We believe in supporting local farmers and maintaining organic farming practices.",
      city: "Kano",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "6",
    name: "Ripe Bananas",
    category: "Fruits",
    price: "700",
    description: "Sweet bananas, perfect for snacking.",
    stock: "300",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Banana Bliss Farm",
      about:
        "Banana Bliss Farm is dedicated to producing the sweetest bananas without the use of harmful pesticides. We cultivate our bananas with care, ensuring they ripen naturally under the sun. Our goal is to provide our customers with delicious fruit while promoting sustainable agricultural practices.",
      city: "Port-harcourt",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "7",
    name: "Organic Carrots",
    category: "Vegetables",
    price: "900",
    description: "Crunchy organic carrots, rich in nutrients.",
    stock: "110",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Rainbow Roots Farm",
      about:
        "Rainbow Roots Farm is a vibrant farm dedicated to growing colorful, organic vegetables. Our carrots are cultivated with care, ensuring they are free from chemicals and full of flavor. We prioritize environmental stewardship and community engagement in all our farming practices.",
      city: "Abuja",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "8",
    name: "Sweet Strawberries",
    category: "Fruits",
    price: "1500",
    description: "Delicious strawberries, perfect for desserts.",
    stock: "90",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Berry Good Farm",
      about:
        "Berry Good Farm is known for its high-quality strawberries, grown in an environmentally friendly manner. Our berries are picked at their peak ripeness to ensure the best flavor. We are passionate about promoting healthy eating and sustainable practices in our community.",
      city: "Owerri",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "9",
    name: "Creamy Avocados",
    category: "Fruits",
    price: "1800",
    description: "Rich avocados, perfect for salads and spreads.",
    stock: "70",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Green Gold Farm",
      about:
        "Green Gold Farm specializes in growing premium avocados that are rich in flavor and nutrients. Our farming methods are designed to enhance the natural growth process while protecting the environment. We take pride in delivering fresh, high-quality produce to our customers.",
      city: "Enugu",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "10",
    name: "Heirloom Tomatoes",
    category: "Vegetables",
    price: "1300",
    description: "Unique heirloom tomatoes with incredible flavor.",
    stock: "60",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Heritage Farms",
      about:
        "Heritage Farms is passionate about preserving traditional farming methods and heirloom varieties. Our heirloom tomatoes are cultivated with care, ensuring a rich flavor and vibrant colors. We believe in the importance of biodiversity in agriculture and strive to offer unique products to our customers.",
      city: "Jos",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "11",
    name: "Organic Peppers",
    category: "Vegetables",
    price: "1100",
    description: "Flavorful organic peppers, great for cooking.",
    stock: "140",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Pepper Paradise",
      about:
        "Pepper Paradise is dedicated to growing a variety of peppers using sustainable practices. Our peppers are vibrant, full of flavor, and grown without chemicals. We believe in creating a healthy food system that benefits both consumers and the environment.",
      city: "Maiduguri",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "12",
    name: "Fresh Cucumbers",
    category: "Vegetables",
    price: "500",
    description: "Crunchy cucumbers, perfect for salads.",
    stock: "200",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Cucumber Cove",
      about:
        "Cucumber Cove specializes in growing fresh, crispy cucumbers in a pesticide-free environment. Our commitment to organic farming allows us to provide our customers with the highest quality produce. We believe that fresh food is essential for a healthy lifestyle.",
      city: "Yola",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "13",
    name: "Zesty Lemons",
    category: "Fruits",
    price: "600",
    description: "Tangy lemons, perfect for cooking and drinks.",
    stock: "130",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Citrus Grove",
      about:
        "Citrus Grove is a vibrant farm known for its delicious citrus fruits. Our lemons are grown naturally, ensuring a zesty flavor that enhances any dish or beverage. We focus on sustainable practices to protect our environment and deliver the best produce to our customers.",
      city: "Abeokuta",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "14",
    name: "Nutritious Kale",
    category: "Vegetables",
    price: "1000",
    description: "Healthy kale, packed with vitamins.",
    stock: "90",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Kale Kingdom",
      about:
        "Kale Kingdom is dedicated to growing nutrient-dense kale and other leafy greens. Our farming practices prioritize health and sustainability, allowing us to offer fresh produce that nourishes both people and the planet. We are passionate about educating our community on healthy eating.",
      city: "Port-harcourt",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "15",
    name: "Honeydew Melons",
    category: "Fruits",
    price: "1400",
    description: "Sweet honeydew melons, perfect for summer.",
    stock: "80",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Melon Meadows",
      about:
        "Melon Meadows focuses on cultivating sweet, juicy melons using organic farming methods. Our honeydew melons are grown with love and care, ensuring they reach peak ripeness before harvest. We are committed to sustainability and supporting local communities.",
      city: "Calabar",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "16",
    name: "Savory Garlic",
    category: "Herbs",
    price: "400",
    description: "Fresh garlic, essential for cooking.",
    stock: "150",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Garlic Garden",
      about:
        "Garlic Garden specializes in growing high-quality garlic using organic techniques. Our garlic is known for its rich flavor and health benefits. We believe in growing food that is both delicious and nourishing, supporting a healthy lifestyle for our community.",
      city: "Kaduna",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "17",
    name: "Fresh Blueberries",
    category: "Fruits",
    price: "2000",
    description: "Sweet blueberries, perfect for snacks and desserts.",
    stock: "50",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Blueberry Bliss Farm",
      about:
        "Blueberry Bliss Farm is dedicated to producing the best blueberries in a sustainable manner. Our berries are handpicked to ensure they are bursting with flavor and nutrients. We are committed to eco-friendly farming practices that support our local environment.",
      city: "Jos",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "18",
    name: "Fresh Ginger",
    category: "Herbs",
    price: "800",
    description: "Aromatic ginger, perfect for cooking and teas.",
    stock: "130",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Ginger Grove",
      about:
        "Ginger Grove specializes in cultivating fresh ginger with a focus on quality and sustainability. Our ginger is grown in nutrient-rich soil, ensuring a robust flavor. We believe in the importance of organic farming for the health of our customers and the planet.",
      city: "Uyo",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "19",
    name: "Rich Figs",
    category: "Fruits",
    price: "2500",
    description: "Sweet figs, perfect for snacking and desserts.",
    stock: "30",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Fig Orchard",
      about:
        "Fig Orchard is dedicated to growing sweet, succulent figs using organic methods. Our figs are handpicked at peak ripeness for maximum flavor. We are committed to sustainable practices that support the health of our environment and the well-being of our community.",
      city: "Ibandan",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
  {
    id: "20",
    name: "Organic Potatoes",
    category: "Vegetables",
    price: "700",
    description: "Versatile organic potatoes for various dishes.",
    stock: "160",
    images: [
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
      "/images/fruits.jpg",
    ],
    farm: {
      name: "Potato Patch",
      about:
        "Potato Patch focuses on growing high-quality organic potatoes. Our farming techniques prioritize soil health and biodiversity, ensuring that our potatoes are not only delicious but also sustainably produced. We are passionate about feeding our community with healthy food options.",
      city: "Kano",
      country: "Nigeria",
    },
    deliveryAvailable: true,
  },
];
