export const farmProducts = [
  {
    id: "1",
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: "3.99",
    description: "Fresh, organic tomatoes grown without pesticides.",
    stock: "120",
    image: "/images/fruits.jpg",
    farmName: "Green Acres Farm",
    location: "Lagos, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "2",
    name: "Free-Range Eggs",
    category: "Animal Products",
    price: "5.5",
    description: "Ethically raised, free-range eggs from organic-fed hens.",
    stock: "200",
    image: "/images/fruits.jpg",
    farmName: "Sunny Hillside Farm",
    location: "Ibadan, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "3",
    name: "Raw Honey",
    category: "Processed Goods",
    price: "12.99",
    description: "100% pure raw honey harvested from wildflowers.",
    stock: "75",
    image: "/images/fruits.jpg",
    farmName: "Bee Kind Apiaries",
    location: "Abuja, Nigeria",
    deliveryAvailable: false,
  },
  {
    id: "4",
    name: "Cassava Flour",
    category: "Grains",
    price: "10.5",
    description: "Gluten-free cassava flour, perfect for baking and cooking.",
    stock: "150",
    image: "/images/fruits.jpg",
    farmName: "Olumo Farms",
    location: "Abeokuta, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "5",
    name: "Yam Tubers",
    category: "Vegetables",
    price: 2.5,
    description: "Fresh, locally grown yam tubers from fertile soils.",
    stock: "500",
    image: "/images/fruits.jpg",
    farmName: "Eko Harvest",
    location: "Osogbo, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "6",
    name: "Catfish",
    category: "Fish",
    price: "8.0",
    description: "Freshly harvested catfish, perfect for grilling or soups.",
    stock: "80",
    image: "/images/fruits.jpg",
    farmName: "Delta Aqua Farms",
    location: "Delta State, Nigeria",
    deliveryAvailable: false,
  },
  {
    id: "7",
    name: "Fresh Okra",
    category: "Vegetables",
    price: "1.2",
    description: "Locally grown okra, a staple for traditional soups.",
    stock: " 90",
    image: "/images/fruits.jpg",
    farmName: "Kano Green Farms",
    location: "Kano, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "8",
    name: "Plantains",
    category: "Fruits",
    price: "1.0",
    description: "Ripe and unripe plantains grown in nutrient-rich soil.",
    stock: "300",
    image: "/images/fruits.jpg",
    farmName: "River Farms",
    location: "Port Harcourt, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "9",
    name: "Pepper (Ata Rodo)",
    category: "Vegetables",
    price: "2.0",
    description: "Fresh, spicy pepper for adding heat to your dishes.",
    stock: "120",
    image: "/images/fruits.jpg",
    farmName: "Red Flame Farms",
    location: "Jos, Nigeria",
    deliveryAvailable: false,
  },
  {
    id: "10",
    name: "Shea Butter",
    category: "Processed Goods",
    price: "15.0",
    description: "Pure, organic shea butter for skin and hair care.",
    stock: "60",
    image: "/images/fruits.jpg",
    farmName: "Natural Glow",
    location: "Kogi, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "11",
    name: "Pineapple",
    category: "Fruits",
    price: "2.5",
    description: "Sweet, juicy pineapples freshly harvested from the farm.",
    stock: "100",
    image: "/images/fruits.jpg",
    farmName: "Sunshine Farms",
    location: "Enugu, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "12",
    name: "Sweet Potatoes",
    category: "Vegetables",
    price: "3.0",
    description:
      "Rich in flavor and nutrients, perfect for roasting or frying.",
    stock: "140",
    image: "/images/fruits.jpg",
    farmName: "Fresh Roots",
    location: "Jos, Nigeria",
    deliveryAvailable: false,
  },
  {
    id: "13",
    name: "Coconut Oil",
    category: "Processed Goods",
    price: "20.0", // per liter
    description: "Cold-pressed coconut oil, ideal for cooking and skincare.",
    stock: "50",
    image: "/images/fruits.jpg",
    farmName: "Tropical Delights",
    location: "Badagry, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "14",
    name: "Corn (Maize)",
    category: "Grains",
    price: "1.5",
    description: "Freshly harvested maize, ready for roasting or cooking.",
    stock: "300",
    image: "/images/fruits.jpg",
    farmName: "Harvest Time Farms",
    location: "Bauchi, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "15",
    name: "Mangoes",
    category: "Fruits",
    price: "3.0",
    description: "Sweet, ripe mangoes grown organically.",
    stock: "250",
    image: "/images/fruits.jpg",
    farmName: "Golden Orchard",
    location: "Benue, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "16",
    name: "Groundnut Oil",
    category: "Processed Goods",
    price: "18.5", // per liter
    description: "Pure groundnut oil, perfect for cooking and frying.",
    stock: "80",
    image: "/images/fruits.jpg",
    farmName: "Nutty Goodness",
    location: "Kano, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "17",
    name: "Bananas",
    category: "Fruits",
    price: "2.0", // per bunch
    description: "Fresh bananas perfect for snacking or smoothies.",
    stock: "180", // in bunches
    image: "/images/fruits.jpg",
    farmName: "Savanna Farms",
    location: "Makurdi, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "18",
    name: "Ginger",
    category: "Spices",
    price: "4.5",
    description: "Fresh ginger with a strong flavor and medicinal properties.",
    stock: "70",
    image: "/images/fruits.jpg",
    farmName: "Healthy Roots",
    location: "Kaduna, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "19",
    name: "Carrots",
    category: "Vegetables",
    price: "1.2",
    description: "Fresh, crunchy carrots, perfect for salads and cooking.",
    stock: "100",
    image: "/images/fruits.jpg",
    farmName: "Root Greens",
    location: "Ogun, Nigeria",
    deliveryAvailable: true,
  },
  {
    id: "20",
    name: "Watermelons",
    category: "Fruits",
    price: "3.0",
    description: "Juicy, refreshing watermelons, perfect for hot days.",
    stock: "90",
    image: "/images/fruits.jpg",
    farmName: "Cool Harvest",
    location: "Kaduna, Nigeria",
    deliveryAvailable: true,
  },
  // {
  //   id: 21,
  //   name: "Soybeans",
  //   category: "Grains",
  //   price: 2.75,
  //   description: "Juicy, refreshing watermelons, perfect for hot days.",
  //   stock: 150,
  //   image: "/images/fruits.jpg",
  //   farmName: "SoyaPlus Farms",
  //   location: "Zaria, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 22,
  //   name: "Onions",
  //   category: "Vegetables",
  //   price: 1.5,
  //   description: "Fresh onions packed with flavor, perfect for cooking.",
  //   stock: 200,
  //   image: "/images/fruits.jpg",
  //   farmName: "Allium Farms",
  //   location: "Sokoto, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 23,
  //   name: "Pepper Soup Spice",
  //   category: "Spices",
  //   price: 5.0, // per packet
  //   description: "Traditional pepper soup spice mix for rich, aromatic soups.",
  //   stock: 100, // in packets
  //   image: "/images/fruits.jpg",
  //   farmName: "Spice Route Farms",
  //   location: "Warri, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 24,
  //   name: "Pawpaw",
  //   category: "Fruits",
  //   price: 2.2, // per piece
  //   description: "Sweet, fresh pawpaw packed with nutrients.",
  //   stock: 90, // in pieces
  //   image: "/images/fruits.jpg",
  //   farmName: "Tropical Harvest",
  //   location: "Asaba, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 25,
  //   name: "Palm Oil",
  //   category: "Processed Goods",
  //   price: 10.0, // per liter
  //   description: "Pure palm oil produced through traditional methods.",
  //   stock: 150, // in liters
  //   image: "/images/fruits.jpg",
  //   farmName: "Gold Palm Farms",
  //   location: "Edo, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 26,
  //   name: "Guinea Fowl",
  //   category: "Poultry",
  //   price: 25.0, // per bird
  //   description: "Freshly raised guinea fowl, ideal for traditional meals.",
  //   stock: 50, // in birds
  //   image: "/images/fruits.jpg",
  //   farmName: "Birdland Farms",
  //   location: "Jos, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 27,
  //   name: "Turmeric",
  //   category: "Spices",
  //   price: 6.0,
  //   description: "Pure turmeric powder known for its medicinal benefits.",
  //   stock: 80,
  //   image: "/images/fruits.jpg",
  //   farmName: "Healing Roots Farms",
  //   location: "Kaduna, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 28,
  //   name: "Cashew Nuts",
  //   category: "Nuts",
  //   price: 8.5,
  //   description: "Crunchy, salted cashew nuts packed with flavor.",
  //   stock: 100,
  //   image: "/images/fruits.jpg",
  //   farmName: "Crunchy Delight",
  //   location: "Kwara, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 29,
  //   name: "Avocado",
  //   category: "Fruits",
  //   price: 3.0, // per piece
  //   description: "Fresh, creamy avocados perfect for salads and spreads.",
  //   stock: 60, // in pieces
  //   image: "/images/fruits.jpg",
  //   farmName: "Avocado Orchard",
  //   location: "Cross River, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 30,
  //   name: "Goat Meat",
  //   category: "Meat",
  //   price: 7.0,
  //   description: "Fresh, tender goat meat for traditional dishes.",
  //   stock: 75,
  //   image: "/images/fruits.jpg",
  //   farmName: "Meaty Choice Farms",
  //   location: "Ekiti, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 31,
  //   name: "Bitterleaf",
  //   category: "Vegetables",
  //   price: 1.5, // per bunch
  //   description: "Freshly harvested bitterleaf for traditional soups.",
  //   stock: 100, // in bunches
  //   image: "/images/fruits.jpg",
  //   farmName: "Green Leaf Farm",
  //   location: "Owerri, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 32,
  //   name: "Soya Milk",
  //   category: "Dairy",
  //   price: 2.5, // per liter
  //   description: "Fresh, homemade soya milk, a great dairy alternative.",
  //   stock: 50, // in liters
  //   image: "/images/fruits.jpg",
  //   farmName: "Healthy Choice Farms",
  //   location: "Minna, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 33,
  //   name: "Cucumber",
  //   category: "Vegetables",
  //   price: 1.0,
  //   description: "Fresh cucumbers, perfect for salads and snacking.",
  //   stock: 120,
  //   image: "/images/fruits.jpg",
  //   farmName: "Cool Greens",
  //   location: "Benin, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 34,
  //   name: "Cabbage",
  //   category: "Vegetables",
  //   price: 2.0,
  //   description: "Crispy, fresh cabbage, great for slaws and salads.",
  //   stock: 100,
  //   image: "/images/fruits.jpg",
  //   farmName: "Veggie Delight",
  //   location: "Jos, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 35,
  //   name: "Peppermint",
  //   category: "Herbs",
  //   price: 3.0, // per bunch
  //   description: "Fresh peppermint leaves with a refreshing aroma.",
  //   stock: 50, // in bunches
  //   image: "/images/fruits.jpg",
  //   farmName: "Herbal Haven",
  //   location: "Ilorin, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 36,
  //   name: "Garden Eggs",
  //   category: "Vegetables",
  //   price: 1.2,
  //   description: "Fresh garden eggs, a healthy snack and meal ingredient.",
  //   stock: 80,
  //   image: "/images/fruits.jpg",
  //   farmName: "Native Harvest",
  //   location: "Anambra, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 37,
  //   name: "Groundnut Paste",
  //   category: "Processed Goods",
  //   price: 5.0,
  //   description: "Freshly made groundnut paste, perfect for snacks and sauces.",
  //   stock: 100,
  //   image: "/images/fruits.jpg",
  //   farmName: "Nutty Delights",
  //   location: "Abuja, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 38,
  //   name: "Cocoa Powder",
  //   category: "Processed Goods",
  //   price: 15.0,
  //   description: "Pure cocoa powder for baking and making hot beverages.",
  //   stock: 40,
  //   image: "/images/fruits.jpg",
  //   farmName: "Choco Farm",
  //   location: "Ondo, Nigeria",
  //   deliveryAvailable: false,
  // },
  // {
  //   id: 39,
  //   name: "Tilapia Fish",
  //   category: "Fish",
  //   price: 9.0,
  //   description: "Fresh tilapia, perfect for grilling or frying.",
  //   stock: 60,
  //   image: "/images/fruits.jpg",
  //   farmName: "Lakeview Fisheries",
  //   location: "Kogi, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 40,
  //   name: "Beef",
  //   category: "Meat",
  //   price: 6.0,
  //   description: "Fresh, tender beef for soups and stews.",
  //   stock: 100,
  //   image: "/images/fruits.jpg",
  //   farmName: "Cattle Ranch",
  //   location: "Adamawa, Nigeria",
  //   deliveryAvailable: true,
  // },
  // {
  //   id: 41,
  //   name: "Millet",
  //   category: "Grains",
  //   price: 1.5,
  //   description: "Whole grain millet, perfect for porridge and baking.",
  //   stock: 150,
  //   image: "/images/fruits.jpg",
  //   farmName: "Golden Grains",
  //   location: "Sokoto, Nigeria",
  //   deliveryAvailable: true,
  // },
];

export default farmProducts;
